name: bloc_demo
description: "A new Flutter project implementing bloc"


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.6
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  injectable: ^2.3.5
  dio: ^5.4.1
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.6.7
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.5.1

flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
